learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs') ),
    url(r'users/', include('users.urls', namespace='users') ),
]

learning_logs/urls.py
"""определяет схемы URL для learning_logs"""
from django.conf.urls import url

from . import views

urlpatterns = [
	# home page
	url(r'^$', views.index, name='index'),
	# show all topic
	url(r'^topics/$', views.topics, name='topics'),
	# page topics
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	# page for new Topic
	url(r'^new_topic/$', views.new_topic, name='new_topic'),
	# page for new Entry
	url(r'^new_entry/$', views.new_entry, name='new_entry'),
	# page for edit Entry
	url(r'^edit_entry/(?P<entry_id>\d+)/$', 
		views.edit_entry, name='edit_entry'),
	# page product
	url(r'^product/(?P<product_id>\d+)/$', views.product, name='product'),

	# add comment product
	url(r'^product/comment/(?P<product_id>\d+)/$', views.comment_product, name='comment_product'),
	# page full text for topic
	url(r'^account/$', views.account, name='account'),
	# page full text for topic
	url(r'^account/(?P<account_id>\d+)/$', views.accounts, name='accounts'),
	# page messages
	url(r'^account/messages/$', views.messages, name='messages'),
	# page messages
	url(r'^account/send_message/(?P<address_id>\d+)/$', views.send_message, name='send_message'),
	
	
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
	#Page enter
	url(r'^login/$', login, {'template_name': 'users/login.html'},
		name='login'),
	#Page exit
	url(r'^logout/$', views.logout_view, name='logout'),
	#Page register
	url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	"""This topic look user"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	#owner = models.ForeignKey(User)
	def __str__(self):
		return self.text

class StatsProduct(models.Model):
	brand = models.CharField(max_length=50)
	type_model = models.CharField(max_length=50)
	type_engine = models.CharField(max_length=50)
	type_drive = models.CharField(max_length=50)
	year_create = models.CharField(max_length=50)
	
class Entry(models.Model):
	"""Information, reading user this topic"""
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	price = models.BigIntegerField()
	file = models.ImageField(upload_to="product")
	name = models.CharField(max_length=200)
	data_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)
	stats = models.ForeignKey(StatsProduct)
	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		if len(self.text) <= 50: 
			return self.text
		else: 
			return self.text[:50] + "..."

class Message(models.Model):
	text = models.TextField()
	sender = models.ForeignKey(User)
	address_id  = models.BigIntegerField()
	title = models.CharField(max_length=200)
	data_added = models.DateTimeField(auto_now_add=True)

class CommentProduct(models.Model):
	text = models.TextField()
	commenter = models.ForeignKey(User)
	product = models.ForeignKey(Entry)



class StatsProductList(models.Model):
	key = models.CharField(max_length=50)
	value = models.CharField(max_length=50)
	

learning_logs/forms.py
from django import forms
from .models import Topic, Entry, Message, CommentProduct, StatsProduct

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['name', 'price', 'text', 'file',]
		labels = {'text': ''}
		
		widgets = {
			'name': forms.TextInput(),
			'price': forms.NumberInput(),
			'text': forms.Textarea( attrs={'cols': 80} ), 
		}

class MessageForm(forms.ModelForm):
	class Meta:
		model = Message
		fields = ['title', 'text']
		labels = {'text': ''}

class CommentProductForm(forms.ModelForm):
	class Meta:
		model = CommentProduct
		fields = ['text',]
		labels = {'text': ''}

class StatsProductForm(forms.ModelForm):
	class Meta:
		model = StatsProduct
		fields = [
			'brand', 
			'type_model', 
			'type_engine', 
			'type_drive', 
			'year_create'
		]
		labels = {'text': ''}	
		

learning_logs/views.py
from django.shortcuts import render, render_to_response

from django.template.defaulttags import register 
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils.translation import ugettext_lazy

from .models import Topic, Entry, User, Message, CommentProduct, StatsProduct, StatsProductList
from .forms import TopicForm, EntryForm, MessageForm, CommentProductForm, StatsProductForm

#consts
COUNT_PRODUCTS_PAGE = 5
COUNT_MESSAGE_PAGE = 5


@register.filter 
def get_item(dictionary, key):
	""" Это нужно для перевода """
	return dictionary.get(key)

# Create your views here.

def index(request):
	"""Home page application Learning Log"""
	return render(request, 'learning_logs/index.html')

 #так видит только владелец статьи
@login_required
def account(request):
	"""show list topic"""
	topic = Topic.objects.first()
	entries = Entry.objects.filter(owner=request.user) 
	entries = this_page(request, entries, COUNT_PRODUCTS_PAGE)
	entries.url = '/account'
	context = {
		'topics': topic, 
		'entries': entries,
		'elements': entries,
	}
	return render(request, 'learning_logs/account.html', context)

def accounts(request, account_id):
	"""show list topic"""
	# Если это личный кабинет текущего пользователя - перейти в его кабинет
	if int(account_id) == int(request.user.id)	:
		return HttpResponseRedirect( reverse('learning_logs:account') )
	topic = Topic.objects.first()	
	the_user = User.objects.get(id=account_id)
	entries = Entry.objects.filter(owner=the_user) 
	entries = this_page(request, entries, COUNT_PRODUCTS_PAGE)
	entries.url = '/account/' + account_id + '/'
	context = {
		'topics': topic, 
		'entries': entries, 
		'the_user': the_user, 
		'elements': entries,
	}
	return render(request, 'learning_logs/accounts.html', context)

def messages(request):
	"""show list messages"""
	my_messages = Message.objects.filter(address_id=request.user.id)
	my_messages = this_page(request, my_messages, COUNT_MESSAGE_PAGE)
	my_messages.url = "/account/messages"
	context = {'messages': my_messages, 'elements': my_messages}
	return render(request, 'learning_logs/messages.html', context) 

def topics(request):
	"""show list topic"""
	topics = Topic.objects.order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
	"""show this topic and his text"""
	topic = Topic.objects.get(id=topic_id)
	products = topic.entry_set.all() #order_by('-date_added')
	products = filter_products(request, products)
	products = this_page(request, products, COUNT_PRODUCTS_PAGE)
	filters = create_filters_list()
	GET = create_get_url(request)
	products.url = "/topics/" + topic_id + "/"
	translate_filter = {
		'Brand': 'Марка', 
		'Type_model': 'Модель', 
		'Type_engine': 'Двигатель', 
		'Type_drive': 'Привод', 
		'Year_create': 'Год' 
	}
	context = {
		'topic': topic, 
		'products': products, 
		'filters': filters,
		'GET': GET,
		'translate_filter': translate_filter,
		'elements': products, 
	}
	return render(request, 'learning_logs/topic.html', context)

def product(request, product_id):
	"""show this product and his text"""
	obj_product = Entry.objects.get(id=product_id)
	comments = CommentProduct.objects.filter(product=obj_product)
	comments = this_page(request, comments, COUNT_MESSAGE_PAGE)
	comments.url = "/product/" + product_id + "/"
	context = {
		'product': obj_product, 
		'comments': comments, 
		'elements': comments
	}
	return render(request, 'learning_logs/product.html', context)


''' *********************************functions form *************************************'''
@login_required
def send_message(request, address_id):
	""" Отправляет сообщение пользователю """
	if request.method != 'POST':
		# Data not send, create empty form
		form = MessageForm()
	else:
		#Data send; tread data
		form = MessageForm(request.POST)
		if form.is_valid():
			new_message = form.save(commit=False)
			new_message.address_id = address_id
			new_message.sender = request.user
			new_message.save()
			return HttpResponseRedirect( reverse('learning_logs:account'))
	context = {'form': form, 'address': address_id}
	return render(request, 'learning_logs/send_message.html', context)

@login_required
def comment_product(request, product_id):
	""" Оставить комментарий под товаром """
	if request.method != 'POST':
		# Data not send, create empty form
		form = CommentProductForm()
	else:
		#Data send; tread data
		form = CommentProductForm(request.POST)
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.product = Entry.objects.get(id=product_id)
			new_comment.commenter = request.user
			new_comment.save()
			return HttpResponseRedirect( reverse('learning_logs:topics'))
	context = {'form': form, 'product': product_id}
	return render(request, 'learning_logs/comment_product.html', context)


@login_required
def new_topic(request):
	"""Определяет новую тему"""
	if request.method != 'POST':
		# Data not send, create empty form
		form = TopicForm()
	else:
		#Data send; tread data
		form = TopicForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect( reverse('learning_logs:topics') )

	context = {'form': form}	
	return render(request, 'learning_logs/new_topic.html', context)

@login_required	
def new_entry(request):
	"""Определяет новое сообщение"""
	topic = Topic.objects.get(id=1)
	if request.method != 'POST':
		#Data not send, create empty form
		form = EntryForm()
	else:
		#Data send; tread data

		post_product = add_filters_product(request)
		form = EntryForm(post_product, request.FILES)
		if form.is_valid():
			new_enrty = form.save(commit=False)
			new_enrty.topic = topic
			new_enrty.owner = request.user
			new_enrty.stats = StatsProduct.objects.last()
			#new_enrty.text = name_row + value_rown
			new_enrty.save()
			return HttpResponseRedirect( reverse('learning_logs:account') )
	filters = create_filters_list()
	context = {'topic': topic, 'form': form, 'filters': filters}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	"""Определяет новое сообщение"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if entry.owner != request.user:
		raise Http404
	if request.method != 'POST':
		#Data not send, create empty form
		form = EntryForm(instance=entry)
	else:
		#Data send; tread data
		post_product = add_filters_product(request, True)
		form = EntryForm(request.POST, request.FILES, instance=entry)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect( reverse('learning_logs:account') )
	filters = create_filters_list()
	context = {'entry': entry, 'topic': topic, 'form': form, 'filters': filters}
	return render(request, 'learning_logs/edit_entry.html', context)	

''' ************************************closes funcions *************************'''

def this_page(request, items, count):
	""" paginator """
	if "page" in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1
	pag = Paginator(items, count)
	try:
		result = pag.page(page_num)
	except:
		result = pag.page(1)
	return result

def create_filters_list():
	""" Полный список фильтров отсортированный по ключам """

	filters = StatsProductList.objects.all()
	result = {}
	for key_filter in filters:
		if key_filter.key in result:
			result[key_filter.key].append(key_filter.value)
		else:
			result[key_filter.key] = [key_filter.value]
	return result


def filter_products(request, products):
	""" Фильтры товаров """
	list_filter = clear_bad_get(request)
	result = []
	for product in products:
		if check_filter(list_filter, product):
			result.append(product)
	return result

def clear_bad_get(request):
	""" Исключить не нужные get данные """
	list_filter = {}
	for key in request.GET:
		if request.GET[key] != '' and  key.lower() != 'page':
			list_filter[key] = request.GET[key]
	return list_filter

def check_filter(list_filter, product):
	for key_get in list_filter:
		if getattr(product.stats, key_get.lower() ) != list_filter[key_get]:
			return False
	return True

def add_filters_product(request, edit = False):
	post_product = {}
	keys = ('name', 'price', 'text')
	for key in keys:
		post_product[key] = request.POST[key]
		request.POST.pop(key)
	request.POST = {k.lower(): v for k, v in request.POST.items()}
	if edit:
		form = StatsProductForm(request.POST, instance=entry)
	else:
		form = StatsProductForm(request.POST)
	if form.is_valid():
		form.save()
	return post_product

def create_get_url(request):
	GET = ""
	for key, value in request.GET.items():
		if key.lower() != 'page':
			GET += "&" + key + "=" + value
	return GET
#неудавшаяся попытка сделать дабавление товара через SQL запрос
#name_row = "(" + ", ".join(request.POST.keys() ) + ")"
		#value_rown = " (NULL, '" + "', '".join( request.POST.values() )  + "')"
		#StatsProduct.objects.raw("INSERT INTO learning_logs_StatsProduct (" + name_row + ") VALUES (" + value_rown + ")" )

learning_logs/templates/learning_logs/account.html
{% extends 'learning_logs/base.html' %}
{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
<h4> Личный кабинет {{ user.username }} </h1>
<p>
  <a href="{% url 'learning_logs:new_entry' %}">Добавить товар</a>
</p>
<p>
  <a href="{% url 'learning_logs:messages' %}"> Мои сообщения</a>
</p>
{% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              Редактировать товар</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        <img src="{{ entry.file.url }}" alt='Модель' style = "max-width: 100%;" />
      </div>

       <div class="panel-body">
        цена {{ entry.price }} руб.
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>

    </div> <!-- panel -->
{% empty %}
    Для данной темы нет записей
{% endfor %}

{% include "learning_logs/paginator.html" %}

{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %} 
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta https-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Портал</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta https-equiv="content-type" content="text/html;charset=utf-8">
    <meta https-equiv="content-type" content="text/html;charset=utf-8">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Auto Club</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %} " />
    <!-- <link href="{% static 'css/master.css' %}" rel="stylesheet"> -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- SWITCHER -->
    <!-- <link rel="stylesheet" id="switcher-css" type="text/css" href="{% static 'assets/switcher/css/switcher.css' %}" media="all" /> -->
    <!-- <link rel="alternate stylesheet" type="text/css" href="{% static 'assets/switcher/css/color1.css' %}" title="color1" media="all" data-default-color="true" /> -->
    <!-- <link rel="alternate stylesheet" type="text/css" href="{% static 'assets/switcher/css/color2.css' %}" title="color2" media="all" /> -->
    <!-- <link rel="alternate stylesheet" type="text/css" href="{% static 'assets/switcher/css/color3.css' %}" title="color3" media="all" /> -->
    <!-- <link rel="alternate stylesheet" type="text/css" href="{% static 'assets/switcher/css/color4.css' %}" title="color4" media="all" /> -->
    <!-- <link rel="alternate stylesheet" type="text/css" href="{% static 'assets/switcher/css/color5.css' %}" title="color5" media="all" /> -->
    <!-- <link rel="alternate stylesheet" type="text/css" href="{% static 'assets/switcher/css/color6.css' %}" title="color6" media="all" /> -->
    
  
    <!-- Статическая навигационная панель -->
    <header>
      <h1> <span style = "color:red">D</span>ALLAS</h1>
      <a class="link_catalog" href="{% url 'learning_logs:index' %}">Каталог товаров</a>
      <a href="/topics/1/">
        <h3>Авто и транспорт</h3>
      </a>
      <form>
        <input type="text" placeholder="Поиск"/>
      </form>

      {% if user.is_authenticated %}
        <div class="sign_in">
          <img src="{% static 'images/sign_in.jpg' %}"/>
          <div class="links">
            <a href="{% url 'learning_logs:account' %}">Привет, {{ user.username }}.</a>
            <a href="{% url 'users:logout' %}"> Выйти</a>
          </div>
        </div>  
      {% else %}
        <div class="sign_in">
          <img src="{% static 'images/sign_in.jpg' %}"/>
          <div class="links">
            <a href="{% url 'users:register' %}"> Регистрация </a>
            <a href="{% url 'users:login' %}"> Войти </a>
          </div>
        </div>
      {% endif %}
    </header>


    <!-- div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div> -->
        <div class="content">
        {% block content %}{% endblock content %}
        </div>
  <!--     </div>
    </div> <!-- --><!--  /container -->
    <!--Main--> 
        <footer>
      <div class="dis_project">
        <h4>О проекте</h4><span>Значимость этих проблем настолько очевидна, что консультация с широким активом в значительной степени обуславливает создание дальнейших направлений развития. Повседневнаяпрактика показывает, что укрепление и развитие структуры обеспечивает широкому кругу (специалистов) участие в формировании модели развития.</span>
      </div>
      <div class="stupid">
        <h4>Последние новости</h4>
        <div class="stupid-text"><img src="{% static 'images/hourglass.png' %}"/>
          <p>Повседневная практика показывает,<br> что постоянное информационно</p>
        </div>
        <div class="stupid-text"><img src="{% static 'images/hourglass.png' %}"/>
          <p>Повседневная практика показывает,<br> что постоянное информационно</p>
        </div>
        <div class="stupid-text"><img src="{% static 'images/hourglass.png' %}"/>
          <p>Повседневная практика показывает,<br> что постоянное информационно</p>
        </div>
      </div>
      <div class="stupid">
        <h4>Правила</h4>
        <div class="stupid-text"><img src="{% static 'images/hourglass.png' %}"/>
          <p>Повседневная практика показывает,<br> что постоянное информационно</p>
        </div>
        <div class="stupid-text"><img src="{% static 'images/hourglass.png' %}"/>
          <p>Повседневная практика показывает,<br> что постоянное информационно</p>
        </div>
        <div class="stupid-text"><img src="{% static 'images/hourglass.png' %}"/>
          <p>Повседневная практика показывает,<br> что постоянное информационно</p>
        </div>
      </div>
      <div class="contact">
        <h4>Контакты</h4><a href="tel:+ 375 (29) 000-00-00 ">+ 375 (29) 000-00-00</a><a href="tel:+ 375 (29) 000-00-00 ">+ 375 (29) 000-00-00</a><a href="pochta@websi">pochta@websi</a>
      </div>
    </footer> 
      <script src="https://code.jquery.com/jquery.min.js"></script>
      <script src="script.js"></script>
    
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

    <script src="{% static 'assets/rendro-easy-pie-chart/dist/jquery.easypiechart.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.easypiechart.min.js' %}"></script>
    <script src="{% static 'js/classie.js' %}"></script>

    <!--Switcher-->
    <script src="{% static 'assets/switcher/js/switcher.js' %}"></script>
    <!--Owl Carousel-->
    <script src="{% static 'assets/owl-carousel/owl.carousel.min.js' %}"></script>
    <!--bxSlider-->
    <script src="{% static 'assets/bxslider/jquery.bxslider.js' %}"></script>
    <!-- jQuery UI Slider -->
    <script src="{% static 'assets/slider/jquery.ui-slider.js' %}"></script>

    <!--Theme-->
    <script src="{% static 'js/jquery.smooth-scroll.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
  
    <script>
      $('.open-get-list').click(function(){
          $(this).next().children('li:not(.get-active)').slideToggle(100);
      });

      $('.filters_list li').click(function(){
        $(this).parent().children('.get-active').removeClass('get-active').show(0);
        $(this).addClass('get-active');
        console.log("Помогите, меня положили в подвал, я хочу выбраться отсюда!");
        $(this).parent().children('.get-input').attr("value", $(this).attr("value") );
      });
    </script>

  </body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">
      {{ topic }}
  </a></p>
  <p>Изменить сообщение:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'  enctype="multipart/form-data">
    {% csrf_token %}
    <div class="b-items__aside-main-body">
			<div class="b-items__aside-main-body-item">

				{% for key, values  in filters.items %}
				<label> {{ key }} </label>
				<div>
					<select name="{{ key }}" class="m-select">
						{% for value in values %}	
							<option value="{{ value }}" selected=""> {{ value }} </option>
						{% endfor %}
						<option value="" selected=""> Не выбрано </option>
					</select>
					<span class="fa fa-caret-down"></span>
				</div>
				{% endfor %}

			</div>
		</div>
    {{ form.as_p }}
    <button name='submit'> Сохранить изменения</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block header %}

  <div class='jumbotron'>
    <h1>Добро пожаловать на сайт</h1>        
  </div>
{% endblock header %}
{% block content %}
 
  <h2>
    <a href="{% url 'users:register' %}"> Региистрация </a> 
    необходима для  полноценной работы с сайтом.
  </h2>
  <h2>
    Без авторизации вы можете только просматривать сайт.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/messages.html
{% extends 'learning_logs/base.html' %}
{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
<h4> Личный кабинет {{ user.username }} </h1>

{% for message in messages %}
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3>
           <a href = "{% url 'learning_logs:accounts' message.sender.id %}">
              {{ message.sender.username }}
           </a>
        </h3>
      </div>
      <div class="panel-body">
      	<h5> Тема: {{ message.title }} </h5>
        {{ message.text|linebreaks }}
      </div>

    </div> <!-- panel -->
{% empty %}
    Сообщений нет
{% endfor %}


{% include "learning_logs/paginator.html" %}

<!-- {% if messages.paginator.num_pages > 1 %}
  <div class="b-items__pagination wow zoomInUp" data-wow-delay="0.5s">
    <div class="b-items__pagination-main">
      {% if messages.has_previous %}
        <a href="{% url 'learning_logs:messages' %}?page={{messages.previous_page_number}}" class="m-left">
          <span class="fa fa-angle-left"></span>
        </a>
      {% endif %}
      
      {% for page in messages.paginator.page_range %}
      
        {% if messages.number == page %}
          <span class="m-active"> 
            {{ page }} 
          </span>
        {% else %}
          <span>
            <a href="{% url 'learning_logs:messages' %}?page={{page}}"> 
              {{ page }} 
            </a>
          </span>
        {% endif %}
        
      {% endfor %}
      
      {% if messages.has_next %}
        <a href="{% url 'learning_logs:messages' %}?page={{messages.next_page_number}}" class="m-right">
          <span class="fa fa-angle-right"></span>
        </a> 
      {% endif %}  
    </div>
  </div>
{% endif %} -->

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
  	<p>
		<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  	</p>
  	<p>Введите описание товара:</p>

  	<form action="{% url 'learning_logs:new_entry' %}" method='post' enctype="multipart/form-data">
		{% csrf_token %}
		<div class="b-items__aside-main-body">
			<div class="b-items__aside-main-body-item">

				{% for key, values  in filters.items %}
				<label> {{ key }} </label>
				<div>
					<select name="{{ key }}" class="m-select">
						{% for value in values %}	
							<option value="{{ value }}" selected=""> {{ value }} </option>
						{% endfor %}
						<option value="" selected=""> Не выбрано </option>
					</select>
					<span class="fa fa-caret-down"></span>
				</div>
				{% endfor %}

			</div>
		</div>
	    
	    {{ form.as_p }}
    	<button name='submit'>Добавить сообщение</button>
  	</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method='post'
      class="form">
{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Добавить тему</button>
    {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic11.html
{% extends 'learning_logs/base.html' %}
{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
<p>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Добавить новое сообщение</a>
</p>
{% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              Редактировать сообщение</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
{% empty %}
    Для данной темы нет записей
{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
  <h1>Темы</h1>
{% endblock header %}
{% block content %}
<ul>
{% for topic in topics %}
<li>
    <h3>
		<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	</h3>
</li>
{% empty %}
<li>Нет созданных тем</li>
{% endfor %}
</ul>
  <h3><a href="{% url 'learning_logs:new_topic' %}">Добавить новую тему:</h3>
{% endblock content %}